---
version: "3.9"

services:
  database:
    image: "postgres"
    environment:
      POSTGRES_USER: song
      POSTGRES_PASSWORD: song
      POSTGRES_DB: song
    ports:
      - 5432:5432
    healthcheck:
      # https://github.com/peter-evans/docker-compose-healthcheck/issues/16
      test:
        [
          "CMD-SHELL",
          "pg_isready",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
