---
services:
  database:
    image: "postgres" # use latest official postgres version
    environment:
      POSTGRES_USER: song
      POSTGRES_PASSWORD: song
      POSTGRES_DB: song
    ports:
      - 5432:5432
